Transform: "AWS::Serverless-2016-10-31"
Resources:
  DataCloudS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "rag-bucket-data-cloud-${AWS::StackName}"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt DataCloudNotificationFunction.Arn

  DataCloudRagRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "DataCloudRagPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource: !Ref DataCloudSecretsManagerSecret
              - Effect: "Allow"
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:Scan"
                Resource: !GetAtt DataCloudDynamoDBTable.Arn
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:List*"
                  - "s3:Get*"
                  - "s3:DeleteObject"
                  - "s3:ListBucket"
                  - "s3:GetBucketNotification"
                  - "s3:PutBucketNotification"
                Resource: !Sub "arn:aws:s3:::rag-test-data-cloud/*"
              - Effect: "Allow"
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"
              - Effect: "Allow"
                "Action":
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

  DataCloudNotificationFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: .
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt DataCloudRagRole.Arn
      Environment:
        Variables:
          SECRET_NAME: DataCloudSecretsManagerSecret
          DYNAMODB_TABLE_NAME: !Ref DataCloudDynamoDBTable

  LambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt DataCloudNotificationFunction.Arn
      Principal: "s3.amazonaws.com"
      SourceArn: !GetAtt DataCloudS3Bucket.Arn

  DataCloudDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "rag-data-cloud-${AWS::StackName}"
      AttributeDefinitions:
        - AttributeName: "jwt"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "jwt"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DataCloudSecretsManagerSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Sub "rag-test-data-cloud-${AWS::StackName}"
      Description: "Secrets for Data Cloud"
      SecretString: !Sub |
        {
          "CLIENT_ID": "2MO_w2n1AqT7ItBzfdas342fdasf897fdas",
          "USERNAME": "john.doe@example.com",
          "LOGIN_URL": "login.salesforce.com",
          "RSA_PRIVATE_KEY": "V3Q2RQZm93eGFvZW13Vys5OGFnQ1dCQTErZGlNMTkrc...",
          "INGESTION_SOURCE_API_NAME": "test-api"
        }

Outputs:
  DataCloudNotificationFunctionArn:
    Description: "ARN of the Data Cloud Notification Lambda Function"
    Value: !GetAtt DataCloudNotificationFunction.Arn

  DataCloudDynamoDBTableName:
    Description: "Name of the created DynamoDB table"
    Value: !Ref DataCloudDynamoDBTable

  DataCloudSecretsManagerSecretArn:
    Description: "ARN of the Secrets Manager secret"
    Value: !Ref DataCloudSecretsManagerSecret

  DataCloudS3BucketName:
    Description: "Name of the created S3 bucket"
    Value: !Ref DataCloudS3Bucket
